---
title: "2025.06.30_figures"
author: "Simon Cooper"
format: pdf
editor: visual
---

## 2025.06.30 Figures

### 0. Set-up.

```{r setup, include = FALSE}

# Clearing environment.
rm(list=ls())

# Setting working directory.
setwd("/Users/simoncooper/Documents/measles")

# Loading data.
load("2025.06.30_clean_brazil_data.RData")
df <- data_clean
rm(data_clean)

# Loading relevant packages.
library(tidyverse)
library(colorspace)

```

#### Making cases and deaths per 100,000 variables.

```{r}

df <- df %>%
  mutate(
    measles_cases_p100k = (measles_cases / population) * 100000,
    measles_deaths_p100k = (measles_deaths / population) * 100000,
    mumps_deaths_p100k = (mumps_deaths / population) * 100000,
    whooping_deaths_p100k = (whooping_deaths / population) * 100000)

save(df, file = "2025.06.30.3_clean_brazil_data.RData")

```

### 1. Measles.

#### Vaccinations, national.

```{r}

# View(df)

# Calculating national average vaccination rate.
nat_avg_vax <- df %>%
  group_by(year) %>%
  summarize(weighted_avg_coverage = weighted.mean(coverage, population, na.rm = TRUE))

# Plotting.
ggplot(nat_avg_vax, aes(x = year, y = weighted_avg_coverage))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Vaccination Coverage",
       title = "National Measles Vaccination Coverage, 1996-2023")

```

#### Vaccinations, regions.

```{r}

# Calculating region average vaccination rate.
region_avg_vax <- df %>%
  group_by(year, region) %>%
  summarize(weighted_avg_coverage = weighted.mean(coverage, population, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(region_avg_vax, aes(x = year, y = weighted_avg_coverage, color = region))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Vaccination Coverage",
       title = "Regional Measles Vaccination Coverage, 1996-2023")

```

#### Vaccinations, federal states.

```{r}

# Calculating state average vaccination rate.
state_avg_vax <- df %>%
  group_by(year, state_name) %>%
  summarize(weighted_avg_coverage = weighted.mean(coverage, population, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(state_avg_vax, aes(x = year, y = weighted_avg_coverage))+
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Measles Vaccination Coverage",
       title = "State Measles Vaccination Coverage, 1996-2023")

```

#### Cases, national.

```{r}

# Summing cases.
nat_cases <- df %>%
  group_by(year) %>%
  summarize(cases = sum(measles_cases, na.rm = TRUE))

nat_cases_prop <- df %>%
  group_by(year) %>%
  summarize(cases_prop = sum(measles_cases_p100k, na.rm = TRUE))

# Plotting.
ggplot(nat_cases, aes(x = year, y = cases))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Cases",
       title = "National Measles Cases, 1996-2023")

ggplot(nat_cases_prop, aes(x = year, y = cases_prop))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Cases per 100,000",
       title = "National Measles Cases per 100,000, 1996-2023")

```

#### Cases, regional.

```{r}

# Summing cases.
region_cases <- df %>%
  group_by(year, region) %>%
  summarize(cases = sum(measles_cases, na.rm = TRUE), .groups = 'drop')

region_cases_prop <- df %>%
  group_by(year, region) %>%
  summarize(cases_prop = sum(measles_cases_p100k, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(region_cases, aes(x = year, y = cases, color = region))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Cases",
       title = "Regional Measles Cases, 1996-2023")

ggplot(region_cases_prop, aes(x = year, y = cases_prop, color = region))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Cases per 100,000",
       title = "Regional Measles Cases per 100,000, 1996-2023")

```

#### Cases, federal states.

```{r}

# Summing cases.
state_cases <- df %>%
  group_by(year, state_name) %>%
  summarize(cases = sum(measles_cases, na.rm = TRUE), .groups = 'drop')

state_cases_prop <- df %>%
  group_by(year, state_name) %>%
  summarize(cases_prop = sum(measles_cases_p100k, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(state_cases, aes(x = year, y = cases))+
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Measles Cases",
       title = "State Measles Cases, 1996-2023")

ggplot(state_cases_prop, aes(x = year, y = cases_prop))+
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Measles Cases per 100,000",
       title = "State Measles Cases per 100,000, 1996-2023")

```

#### Mortality, national.

```{r}

# Summing deaths.
nat_deaths <- df %>%
  group_by(year) %>%
  summarize(deaths = sum(measles_deaths, na.rm = TRUE))

nat_deaths_prop <- df %>%
  group_by(year) %>%
  summarize(deaths_prop = sum(measles_deaths_p100k, na.rm = TRUE))

# Plotting.
ggplot(nat_deaths, aes(x = year, y = deaths))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Deaths",
       title = "National Measles Deaths, 1996-2023")

ggplot(nat_deaths_prop, aes(x = year, y = deaths_prop))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Deaths per 100,000",
       title = "National Measles Deaths per 100,000, 1996-2023")

```

#### Mortality, regions.

```{r}

# Summing deaths.
region_deaths <- df %>%
  group_by(year, region) %>%
  summarize(deaths = sum(measles_deaths, na.rm = TRUE), .groups = 'drop')

region_deaths_prop <- df %>%
  group_by(year, region) %>%
  summarize(deaths_prop = sum(measles_deaths_p100k, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(region_deaths, aes(x = year, y = deaths, color = region))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Deaths",
       title = "Regional Measles Deaths, 1996-2023")

ggplot(region_deaths_prop, aes(x = year, y = deaths_prop, color = region))+
  geom_line() +
  labs(x = "Year",
       y = "Measles Deaths per 100,000",
       title = "Regional Measles Deaths per 100,000, 1996-2023")

```

#### Mortality, federal states.

```{r}

# Summing cases.
state_deaths <- df %>%
  group_by(year, state_name) %>%
  summarize(deaths = sum(measles_deaths, na.rm = TRUE), .groups = 'drop')

state_deaths_prop <- df %>%
  group_by(year, state_name) %>%
  summarize(deaths_prop = sum(measles_deaths_p100k, na.rm = TRUE), .groups = 'drop')

# Plotting.
ggplot(state_deaths, aes(x = year, y = deaths))+
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Measles Deaths",
       title = "State Measles Deaths, 1996-2023")

ggplot(state_deaths_prop, aes(x = year, y = deaths_prop))+
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Measles Deaths per 100,000",
       title = "State Measles Deaths per 100,000, 1996-2023")

```

### 2. Mumps and whooping cough. 

#### Mortality, national.

```{r}

# Summing deaths.
nat_deaths_all <- df %>%
  group_by(year) %>%
  summarize(
    measles_deaths = sum(measles_deaths, na.rm = TRUE),
    mumps_deaths = sum(mumps_deaths, na.rm = TRUE),
    whooping_deaths = sum(whooping_deaths, na.rm = TRUE))

nat_deaths_all_prop <- df %>%
  group_by(year) %>%
  summarize(
    measles_deaths_prop = sum(measles_deaths_p100k, na.rm = TRUE),
    mumps_deaths_prop = sum(mumps_deaths_p100k, na.rm = TRUE),
    whooping_deaths_prop = sum(whooping_deaths_p100k, na.rm = TRUE))

# Making into long format.
nat_deaths_long <- nat_deaths_all %>%
  pivot_longer(cols = c(measles_deaths, mumps_deaths, whooping_deaths),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths" ~ "Measles",
    disease == "mumps_deaths" ~ "Mumps",
    disease == "whooping_deaths" ~ "Whooping Cough",
    TRUE ~ disease))

nat_deaths_prop_long <- nat_deaths_all_prop %>%
  pivot_longer(cols = c(measles_deaths_prop, mumps_deaths_prop, whooping_deaths_prop),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths_prop" ~ "Measles",
    disease == "mumps_deaths_prop" ~ "Mumps",
    disease == "whooping_deaths_prop" ~ "Whooping Cough",
    TRUE ~ disease))

# Plotting.
ggplot(nat_deaths_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  labs(x = "Year",
       y = "Deaths",
       title = "National Deaths by Disease, 1996-2023",
       color = "Disease")

ggplot(nat_deaths_prop_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  labs(x = "Year",
       y = "Deaths",
       title = "National Deaths per 100,000 by Disease, 1996-2023",
       color = "Disease")

```

#### Mortality, regions.

```{r}

# Summing deaths.
region_deaths_all <- df %>%
  group_by(year, region) %>%
  summarize(
    measles_deaths = sum(measles_deaths, na.rm = TRUE),
    mumps_deaths = sum(mumps_deaths, na.rm = TRUE),
    whooping_deaths = sum(whooping_deaths, na.rm = TRUE),
    .groups = 'drop')

region_deaths_all_prop <- df %>%
  group_by(year, region) %>%
  summarize(
    measles_deaths = sum(measles_deaths_per100k, na.rm = TRUE),
    mumps_deaths = sum(mumps_deaths_p100k, na.rm = TRUE),
    whooping_deaths = sum(whooping_deaths_p100k, na.rm = TRUE),
    .groups = 'drop')

# Making into long format.
region_deaths_long <- region_deaths_all %>%
  pivot_longer(cols = c(measles_deaths, mumps_deaths, whooping_deaths),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths" ~ "Measles",
    disease == "mumps_deaths" ~ "Mumps",
    disease == "whooping_deaths" ~ "Whooping Cough",
    TRUE ~ disease))

region_deaths_prop_long <- region_deaths_all_prop %>%
  pivot_longer(cols = c(measles_deaths, mumps_deaths, whooping_deaths),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths" ~ "Measles",
    disease == "mumps_deaths" ~ "Mumps",
    disease == "whooping_deaths" ~ "Whooping Cough",
    TRUE ~ disease))

# Plotting.
ggplot(region_deaths_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  facet_wrap(~region) +
  labs(x = "Year",
       y = "Deaths",
       title = "Regional Deaths by Disease, 1996-2023",
       color = "Disease")

ggplot(region_deaths_prop_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  facet_wrap(~region) +
  labs(x = "Year",
       y = "Deaths",
       title = "Regional Deaths per 100,000 by Disease, 1996-2023",
       color = "Disease")

```

#### Mortality, federal states.

```{r}

# Summing deaths.
states_deaths_all <- df %>%
  group_by(year, state_name) %>%
  summarize(
    measles_deaths = sum(measles_deaths, na.rm = TRUE),
    mumps_deaths = sum(mumps_deaths, na.rm = TRUE),
    whooping_deaths = sum(whooping_deaths, na.rm = TRUE),
    .groups = 'drop')

states_deaths_all_prop <- df %>%
  group_by(year, state_name) %>%
  summarize(
    measles_deaths = sum(measles_deaths_per100k, na.rm = TRUE),
    mumps_deaths = sum(mumps_deaths_p100k, na.rm = TRUE),
    whooping_deaths = sum(whooping_deaths_p100k, na.rm = TRUE),
    .groups = 'drop')

# Making into long format.
states_deaths_long <- states_deaths_all %>%
  pivot_longer(cols = c(measles_deaths, mumps_deaths, whooping_deaths),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths" ~ "Measles",
    disease == "mumps_deaths" ~ "Mumps",
    disease == "whooping_deaths" ~ "Whooping Cough",
    TRUE ~ disease))

states_deaths_prop_long <- states_deaths_all_prop %>%
  pivot_longer(cols = c(measles_deaths, mumps_deaths, whooping_deaths),
               names_to = "disease",
               values_to = "deaths") %>%
  mutate(disease = case_when(
    disease == "measles_deaths" ~ "Measles",
    disease == "mumps_deaths" ~ "Mumps",
    disease == "whooping_deaths" ~ "Whooping Cough",
    TRUE ~ disease))

# Plotting.
ggplot(states_deaths_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Deaths",
       title = "State Deaths by Disease, 1996-2023",
       color = "Disease")

ggplot(states_deaths_prop_long, aes(x = year, y = deaths, color = disease)) +
  geom_line() +
  facet_wrap(~state_name) +
  labs(x = "Year",
       y = "Deaths",
       title = "State Deaths per 100,000 by Disease, 1996-2023",
       color = "Disease")

```
